import { NAV_MENUS, NAV_CONFIG_TREE } from './nav'
import { MONITOR_TYPES_FIELDS, MONITOR_PARAMS_FIELDS, TUNNELS_FIELDS, WIRES_FIELDS, SECTIONS_FIELDS, MONITOR_DEVICES_FIELDS, MONITOR_CAMERAS_FIELDS } from './fields'


const FIELDS = { MONITOR_TYPES_FIELDS, MONITOR_PARAMS_FIELDS, TUNNELS_FIELDS, WIRES_FIELDS, SECTIONS_FIELDS, MONITOR_DEVICES_FIELDS, MONITOR_CAMERAS_FIELDS }

export {
  NAV_MENUS,
  NAV_CONFIG_TREE,
  FIELDS
}